### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by NadiiaBulmak**
- [DEMO LINK](https://NadiiaBulmak.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://NadiiaBulmak.github.io/layout_search-bar-airbnb/report/html_report/)

Test report link мабуть не працює, не знаю, як пофіксити

### CODE REVIEW

**Review by anastasiia-tilikina — CHANGES_REQUESTED** [review]
Pls fix test link.
If you have any problems - feel free to ask your questions in chat

**Comment by NadiiaBulmak** [comment]
> Pls fix test link. If you have any problems - feel free to ask your questions in chat

I fixed test link, pls check.
Thank you

**Review by lerastarynets — APPROVED** [review]
lgtm 🚀

**Review by lerastarynets — APPROVED** [review]
lgtm 🚀

**Pull request closed without merging**
