### PR TITLE
Add big and small search bars

### PR DESCRIPTION
**Pull request by ik-web**
- [DEMO LINK](https://ik-web.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://ik-web.github.io/layout_search-bar-airbnb/report/html_report/)

### CODE REVIEW

**Review by mykola-koval — CHANGES_REQUESTED** [review]
good job 👍 
But text should be bold only on focus

**Comment by ik-web** [comment]
Ok. Could you explain me this moment. As I see it in the mockup and in the requirements, we should have font-weight 300 for defoult text and it should change when we are typing our text in the search bar. I see only normal (400) font-weight in the mockup and I can't find something about font-weight (bolt). Could you help me to get it?

**Comment by mykola-koval** [comment]
> Ok. Could you explain me this moment. As I see it in the mockup and in the requirements, we should have font-weight 300 for defoult text and it should change when we are typing our text in the search bar. I see only normal (400) font-weight in the mockup and I can't find something about font-weight bold (800). Could you help me to get it?

here's the screenshot from the mockup
image

we should connect both font-faces as font-family "Avenir" but with different font-weight
and on focus we change only the font-weight

does it sound good to you? if you have any questions, ask right away

**Comment by ik-web** [comment]
I'm sorry... I understood you now but for me it [shows](https://prnt.sc/peQPyn4yqS-o) 400 normal... And when I looked an approved work another student, he has the same weight it's 400 or it would be 300 for all behaviors, I dont remember it correctly

**Review by Olexandr6 — APPROVED** [review]

**Pull request closed without merging**
