### PR TITLE
Search Bar are Done

### PR DESCRIPTION
**Pull request by M-Grisha**
https://M-Grisha.github.io/layout_search-bar-airbnb/
https://M-Grisha.github.io/layout_search-bar-airbnb/report/html_report/

### CODE REVIEW

**Comment by M-Grisha** [comment]
https://m-grisha.github.io/layout_search-bar-airbnb/
https://m-grisha.github.io/layout_search-bar-airbnb/report/html_report/

**Review by ArturErmolenko — CHANGES_REQUESTED** [review]
Links doesn't work ,please redeploy your work

**Comment by M-Grisha** [comment]
> Links doesn't work ,please redeploy your work

I dont know how. cry

**Comment by M-Grisha** [comment]
I make changes. check please

**Comment by M-Grisha** [comment]
> Links doesn't work ,please redeploy your work

I make changes. check please

**Review by ArturErmolenko — APPROVED** [review]
Well done 👍

**Pull request closed without merging**
