### PR TITLE
first draft

### PR DESCRIPTION
**Pull request by kq333**
[DEMO LINK](https://kq333.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://kq333.github.io/layout_search-bar-airbnb/report/html_report/)

### CODE REVIEW

**Review by michalcywka — CHANGES_REQUESTED** [review]
Links are not working

**Comment by kq333** [comment]
> Links are not working

seems ok now

**Review by michalcywka — CHANGES_REQUESTED** [review]
Screenshot 2023-03-09 at 09 04 17
Please check the task description, search-bar should have 100% width. Also as you can see in the attached screenshot, the green color shows input area. This searchbar should be clickable and selectable on it's full width (not only on the green area).

**Review by michalcywka — CHANGES_REQUESTED** [review]
Font weight does not change after typing

**Review by michalcywka — CHANGES_REQUESTED** [review]
Please refer to the mockup and see what should happen when input is in `focus`

**Review by michalcywka — CHANGES_REQUESTED** [review]
Checklist point 12

**Review by michalcywka — CHANGES_REQUESTED** [review]
Checklist point 12

**Pull request closed without merging**
